CREATE TABLE comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id   BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author    VARCHAR(255)                            NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author    VARCHAR(255)                            NOT NULL,
    subject   VARCHAR(255)                            NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    likes     INTEGER                                 NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);