CREATE TABLE comment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_post_id BIGINT                                  NOT NULL,
    text           text,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PARENTPOST FOREIGN KEY (parent_post_id) REFERENCES post (id);
